#!/usr/bin/env bash
#for loop to locate directories in list format, excluding the beginning of the directory name
for x in *; do 
	sed "s/.*-/-/";
	if [ -f "$x" ]; then
                echo "$x"
	fi	
done
