#!/usr/bin/env bash
#if statement for listing file information
if test -f 'school.txt' ; then
	echo 'school file exists'
		if test -z 'school.txt' ; then
			echo 'school file is empty'
		else				
			echo 'school file is not empty'
		fi
		if test -f 'school.txt' ; then
			echo 'school is a regular file'
		elif test -d 'school.txt' ; then				
			:
		fi
elif ! test -f 'school.txt' ; then
	echo 'school file does not exist'	
fi
